#%RAML 0.8
title: Contact Types API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Contact Types API
    content: This documents the API calls that can be made to query and manage contact types for preferred-contact settings

schemas:
  - contacttype: !include schema/contacttype.json
  - contacttypes: !include schema/contacttypes.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error: !include ../raml-util/schemas/error.schema
  - parameters: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - pageable: !include ../raml-util/traits/pageable.raml
  - searchable: !include ../raml-util/traits/searchable.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-delete-only: !include ../raml-util/rtypes/get-delete.raml

/contact-types:
  type:
    collection:
      exampleCollection: !include examples/contacttypes.json
      exampleItem: !include examples/contacttype.json
      schemaCollection: contacttypes
      schemaItem: contacttype
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of contact types
  post:
    description: Create a new contact type
    is: [validate]
  /{contacttypeId}:
    description: Pass in the contact type identifier
    type:
      collection-item:
        exampleItem: !include examples/contacttype.json
        schema: contacttype
